[
build-system
]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[
project
]
name = "rpcv2-hist-sdk"
version = "0.1.0"
description = "Python SDK for rpcv2-hist"
readme = "README.md"
license = {text = "AGPL-3.0"}
requires-python = ">=3.8"
dependencies = ["httpx>=0.24"]

[
project.optional-dependencies
]
dev = ["pytest>=7", "black", "mypy"]