# AGPL-3.0
openapi: 3.0.3
info:
  title: RPCv2-Hist
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /block/{slot}:
    get:
      summary: Get block
      parameters:
        - name: slot
          in: path
          required: true
          schema: { type: integer }
        - name: commitment
          in: query
          schema: { type: string, enum: [processed, confirmed, finalized], default: finalized }
      responses:
        '200':
          description: block
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Block' }
  /tx/{signature}:
    get:
      summary: Get transaction
      parameters:
        - name: signature
          in: path
          required: true
          schema: { type: string }
        - name: commitment
          in: query
          schema: { type: string, enum: [processed, confirmed, finalized], default: finalized }
      responses:
        '200':
          description: transaction
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Transaction' }
  /sigs/{address}:
    get:
      summary: Get signatures for address
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
        - name: limit
          in: query
          schema: { type: integer, default: 100, maximum: 1000 }
        - name: before
          in: query
          schema: { type: string }
        - name: until
          in: query
          schema: { type: string }
      responses:
        '200':
          description: signatures
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/SignatureInfo' }
components:
  schemas:
    Block:
      type: object
      properties:
        slot: { type: integer }
        blockhash: { type: string }
        parentSlot: { type: integer }
        blockTime: { type: integer }
        height: { type: integer }
    Transaction:
      type: object
      properties:
        signature: { type: string }
        slot: { type: integer }
        blockTime: { type: integer }
        signer: { type: string }
        fee: { type: integer }
        computeUnits: { type: integer }
        err: { type: string, nullable: true }
    SignatureInfo:
      type: object
      properties:
        signature: { type: string }
        slot: { type: integer }
        err: { type: string, nullable: true }
        memo: { type: string, nullable: true }
        blockTime: { type: integer }