# AGPL-3.0
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.8
        ports:
          - 9000:9000
        options: --ulimit nofile=262144:262144
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go mod download
      - run: make test
      - run: make bench
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest